# Generated by Django 4.2.3 on 2023-08-18 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время не может быть меньше 1 минуты.'), django.core.validators.MaxValueValidator(5000, 'Время не может быть больше 5000 минут.')], verbose_name='Время приготовления(в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipe.tag', verbose_name='Тэг рецепта'),
        ),
    ]
